language: node_js

cache:
  directories:
    - "node_modules"
    - "~/.npm"

node_js:
  - "12"

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - sexyespadachin1@gmail.com
      - joseiriarte2102@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy from Travis CI"
  on:
    branch: master